### ISSUE TITLE
printLogs: 'always' causes nothing to be printed in files

### ISSUE THREAD

**Issue by csvan** [archfz/cypress-terminal-report#43] opened 2020-08-20 15:23 UTC
Tested on Cypress 5.0 and latest version of cypress-terminal-report.

My config looks like this:

```
module.exports = (on, config) => {
  require('cypress-terminal-report/src/installLogsPrinter')(on, {
    printLogs: 'always',
    outputRoot: 'cypress/logs/',
    outputTarget: {
      'testLogs.txt': 'txt',
      'testLogs.json': 'json',
    }
  });
```

The above causes `testLogs.txt` to be empty, and `testLogs.json` to contain:

```
,
,
,
,
,
{}
```

However, if I set it to 'onFail' or do not specify it at all, error logs are printed normally.

**Comment by archfz** [comment] 2020-08-20 15:47
Dose this only apply on file exports or do you not get any logs in the terminal either.

**Comment by csvan** [comment] 2020-08-20 16:10
@archfz it affects the terminal as well from what I can see.

**Comment by archfz** [comment] 2020-08-20 21:46
The issue seems to be that you send the printLogs: 'always' to the plugin install rather then the support install. Please check the readme. While trying to reproduce I noticed some unrelated issues with output generation. 

But I am curious how you got that JSON output. Did your run the tests from GUI? Did you run one spec file or multiple? Did all pass?

**Comment by archfz** [comment] 2020-08-29 09:52
@csvan I will close this for now. A feature will be upcomming with JSON schema validation on options. If you still have problems feel free to reopen.

**Closed by archfz** 2020-08-29 09:52 UTC
Labels: clarification
