### ISSUE TITLE
Interceptor overrides are disabled

### ISSUE THREAD

**Issue by aayvazyan-tgm** [archfz/cypress-terminal-report#120] opened 2021-09-30 13:31 UTC
If interceptors override each other, then the newest matching interceptor should be called.
Somehow this plugin disables this order.

The workaround is to disable/remove 'cy:intercept' in options.collectTypes

**Comment by archfz** [comment] 2021-09-30 15:05
Can you check here https://github.com/archfz/cypress-terminal-report/blob/master/src/collector/LogCollectCypressIntercept.js . I don't see how else this should be done, we are calling the previous overwrite.

**Comment by aayvazyan-tgm** [comment] 2021-10-02 17:55
The code looks perfectly fine. Still, it seems to cause a side effect within cypress.

**Comment by archfz** [comment] 2021-10-02 18:10
Can you provide reproduction steps?

**Comment by aayvazyan-tgm** [comment] 2021-10-04 10:40
![image](https://user-images.githubusercontent.com/5500621/135837178-0bbd2092-86a2-4ccc-bd69-8be692831375.png)

I have setup a minimal project with this bug:
https://github.com/aayvazyan-tgm/cypress-logger-interceptor-bug

**Comment by archfz** [comment] 2021-10-04 14:54
Yeah good catch. The issue is that somehow the return value of the original handler function of `cy.intercept` being override gives a return value, which if not returned in the new handler will cause this issue. Now the strange part that this issue reproduces only in GUI, so it cannot be tested for easily.

**Comment by archfz** [comment] 2021-10-04 15:36
Fixed in 3.3.3.

**Closed by archfz** 2021-10-04 15:36 UTC
