### ISSUE TITLE
Increased flakiness when using plugin

### ISSUE THREAD

**Issue by lidiagc** [archfz/cypress-terminal-report#164] opened 2022-08-30 10:52 UTC
Hello! 

In our application we have several frontend tests using cypress: some end-to-end ones but the majority are component tests. We also use msw to mock all the server requests.

Recently, we have been trying to combat some flakiness in our component tests, so we wanted to integrate `cypress-terminal-report` to get the additional logging for our tests. However, we have noticed our GitLab job that runs the component tests to fail more frequently.

To benchmark our job with and without `cypress-terminal-report`, we ran them on the CI 100 times. We have 68 spec files, which total 331 tests.

- without `cypress-terminal-report`: 68 pipelines passed out of 100
- with `cypress-terminal-report`: 0 pipelines passed out of 100, with an average of 2.5 tests failing per pipeline

Looking at some of the videos of failed tests with the plugin, the tests fail with the error `TypeError: Failed to Fetch`. We think this error comes from msw, and it has happened sometimes on a normal pipeline; however, with the plugin installed it happens way more frequently, becoming really hard to get a green pipeline on consequent retries. Do you have any indication of why this is happening and how we could mitigate the issue?

### Our Environment

- cypress: `9.7.0`
- msw: `0.44.2`
- cypress-terminal-report: `3.5.2`
  -  we haven't been able to upgrade to cypress 10, so we don't have the latest version of `cypress-terminal-report`

`cypress/support/index.js`
```
require("cypress-terminal-report/src/installLogsCollector")();
```

`cypress/plugins/index.js`
```
require("cypress-terminal-report/src/installLogsPrinter")(on, {
    printLogsToConsole: "never",
});
```

**Comment by archfz** [comment] 2022-08-30 11:35
I suppose there is a conflict between the two plugins. What is the reason for using msw over cypress.intercept?

**Comment by lidiagc** [comment] 2022-08-30 12:48
Before cypress, we used Jest for component tests also with msw. Converting from jest to cypress was easier since we could reuse most of the code for the mocked server.

**Comment by archfz** [comment] 2022-08-30 12:58
Can you create a minimal reproduction repo? Since I never used msw it would be harder for me.

**Comment by lidiagc** [comment] 2022-09-01 09:35
Sorry for not getting back to you sooner. I still haven't managed to create a minimal repo.

**Comment by archfz** [comment] 2022-11-07 19:59
Closing for now, feel free to add new details if needed.

**Closed by archfz** 2022-11-07 19:59 UTC
