### ISSUE TITLE
Skipped tests in second describe() block hangs during test execution

### ISSUE THREAD

**Issue by thaiching** [archfz/cypress-terminal-report#114] opened 2021-08-05 20:01 UTC
During the test execution, the skipped tests within the second describe() block will hang if there are more than one describe blocks within a spec file.

Eg: Here is a skeleton of my spec test file

  ```
describe('describe block One, () => {
    before(() => {
      cy.setupAllRoutes();
      cy.visit(`https://www.google.co.uk`);
    });

    // This will get skipped during execution, which is fine
    it.skip('First skipped IT block in describe one', () => {
    });

    it('Second IT block in describe one', () => {
    });
  });

  describe('describe block TWO, () => {
    beforeEach(() => {
      cy.setupGAMRoute();
      cy.visit(`https://www.google.co.uk`);
    });

  // The test will hang at this point on the skipped test in the second describe block
    it.skip('First Skipped IT block in describe two', () => {
    });

    it('Second IT block in describe Two', () => {
    });
  });
```

  It seems like the skipped tests will be skipped without any issue only on the first describe block in a spec file. If there are more than one describe blocks within a test file, the skipped tests in the subsequent describe() block will not work/skipped

**Comment by archfz** [comment] 2021-08-06 16:26
Cannot reproduce need more context: plugin install options, support install options. Maybe also node version, cypress version, browser used.

**Comment by ThaiChingChong** [comment] 2021-08-09 08:35
Hi @archfz ,
   I'm using the following:

plugins/index.js

```
const del = require('del');
const fs = require('fs-extra');
const path = require('path');
const installLogsPrinter = require('cypress-terminal-report/src/installLogsPrinter');

const getConfigurationByFile = (file) => {
  const pathToConfigFile = `config/cypress.${file}.json`;
  return !!file && fs.readJson(path.join(__dirname, '../', pathToConfigFile));
};

module.exports = (on, config) => {

  installLogsPrinter(on, {
    printLogsToConsole: "onFail",
    collectTestLogs: () => console.log(''),
  });

  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push(
        '--disable-features=CrossSiteDocumentBlockingIfIsolating,CrossSiteDocumentBlockingAlways,IsolateOrigins,site-per-process',
      );
      // launchOptions.args.push('--load-extension=cypress/extensions/iframe-security')
      return launchOptions;
    }
  });

  on('after:spec', (spec, results) => {
    if (results && results.video) {
      // Do we have failures for any retry attempts?
      const failures = results.tests.some((test) => {
        return test.attempts.some((t) => t.state === 'failed');
      });

      if (!failures) {
        // delete the video if the spec passed and no tests retried
        return del(results.video);
      }
    }
  });

  const enviroment = config.env.configFile;
  const configForEnviroment = getConfigurationByFile(enviroment);
  return configForEnviroment || config;
};
```


/support/index.ts

```
import './commands';

const options = {
  collectTypes: ["cy:log", "cy:xhr", "cy:request", "cy:route", "cy:command"],
};

require('cypress-terminal-report/src/installLogsCollector')(options);

Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false;
});

```

Cypress version: 7.7.0
Node version: v12.16.1
Browser: Chrome 92

Thanks.

**Comment by thaiching** [comment] 2021-08-09 08:48
Hi @archfz ,
I'm using the following:

plugins/index.js

```
const del = require('del');
const fs = require('fs-extra');
const path = require('path');
const installLogsPrinter = require('cypress-terminal-report/src/installLogsPrinter');

const getConfigurationByFile = (file) => {
  const pathToConfigFile = `config/cypress.${file}.json`;
  return !!file && fs.readJson(path.join(__dirname, '../', pathToConfigFile));
};

module.exports = (on, config) => {

  installLogsPrinter(on, {
    printLogsToConsole: "onFail",
    collectTestLogs: () => console.log(''),
  });

  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push(
        '--disable-features=CrossSiteDocumentBlockingIfIsolating,CrossSiteDocumentBlockingAlways,IsolateOrigins,site-per-process',
      );
      // launchOptions.args.push('--load-extension=cypress/extensions/iframe-security')
      return launchOptions;
    }
  });

  on('after:spec', (spec, results) => {
    if (results && results.video) {
      // Do we have failures for any retry attempts?
      const failures = results.tests.some((test) => {
        return test.attempts.some((t) => t.state === 'failed');
      });

      if (!failures) {
        // delete the video if the spec passed and no tests retried
        return del(results.video);
      }
    }
  });

  const enviroment = config.env.configFile;
  const configForEnviroment = getConfigurationByFile(enviroment);
  return configForEnviroment || config;
};
```
/support/index.ts

```
import './commands';

const options = {
  collectTypes: ["cy:log", "cy:xhr", "cy:request", "cy:route", "cy:command"],
};

require('cypress-terminal-report/src/installLogsCollector')(options);

Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false;
});
```

Cypress version: 7.7.0
Node version: v12.16.1
Browser: Chrome 92

Thanks.

**Comment by archfz** [comment] 2021-08-10 19:31
I still cannot reproduce with all the configuration and versions added.

Is this happening only in `open` mode or also in `run` mode, meaning in GUI or also in Terminal as well?
If you remove the plugin does it still happen?
Maybe it is something particular the way the test is configured for you. Please check if the following is also hanging the same way:
```js
describe('Test skips', () => {
  beforeEach(() => {
    cy.visit(`https://www.google.co.uk`);
  })
  it("Not skipped 1", () => {
    cy.log('Not skipped 1.')
  })
  it.skip("A skipped test", () => {
    cy.log('Skipped test log.')
  })
  it("Not skipped 2", () => {
    cy.log('Not skipped 2.')
  })
})

describe('2 - Test skips', () => {
  beforeEach(() => {
    cy.visit(`https://www.google.co.uk`);
  })
  it("2 - Not skipped 1", () => {
    cy.log('2 - Not skipped 1.')
  })
  it.skip("2 - A skipped test", () => {
    cy.log('2 - Skipped test log.')
  })
  it("2 - Not skipped 2", () => {
    cy.log('2 - Not skipped 2.')
  })
})
```

Also maybe try to open the inspector in the browser and see if there are any relevant JS errors. What you could also try is to replicate the case in the [cypress-terminal-report-demo](https://github.com/archfz/cypress-terminal-report-demo) project and see if that way it reproduces.

**Comment by thaiching** [comment] 2021-08-11 15:34
Hi @archfz ,
   Thanks for investigating the issue. Sorry I could have given you my sample code to reproduce the issue that will save lots of your investigation time. After trying out your code I couldn't reproduce this issue myself. However I have done some investigation from my side too and noticed that if there are 2 skipped tests within the same describe block, the second skipped test will hang. Here is my sample code for your reference.

```
/// <reference types="cypress" />

  describe('Describe 1', () => {
    before(() => {
      cy.visit(`https://www.google.co.uk`);
    });

    it.skip('Skipped test 1', () => {
      cy.log('first skip');
    });

    it('Test 2', () => {
      cy.log('test 2');
    });
  });

  describe('Describe 2', () => {
    beforeEach(() => {
      cy.visit(`https://www.google.co.uk`);
    });

   // The tests gets hang here
    it.skip('Skipped test 2', () => {
      cy.log('Skipped test 2');
    });

  //This second skipped test seems to be the culprit
    it.skip('Skipped test 3', () => {
      cy.log('Skipped test 3');
    });

    it('Test 3', () => {
      cy.log('Test 3');
    });

    it('Test 4', () => {
      cy.log('Test 4');
    });
  });


```

**Comment by archfz** [comment] 2021-08-18 12:39
Released in 3.3.1

**Closed by archfz** 2021-08-18 12:39 UTC
Labels: bug

**Comment by ThaiChingChong** [comment] 2021-08-20 08:50
Thank you! :)

**Comment by thaiching** [comment] 2021-08-20 08:52
Thank you. Its working fine now :)
