### ISSUE TITLE
Nothing logged when a test fails in a before hook (for example)

### ISSUE THREAD

**Issue by Dicee** [archfz/cypress-terminal-report#76] opened 2021-02-25 19:25 UTC
Hello! Let me start by saying that I really appreciate the effort put into this package, it's useful (something similar should be included in Cypress to be honest).

I've played around with your plugin, but I haven't been able to do some things I wanted. For example, I found that when an error occurs in a `before` hook, nothing was logged. Below is a small snippet to help you reproduce:

```typescript
describe('Example', () => {
    before(() => {
        cy.visit('https://google.com')
        cy.contains('impossible to match').click()
    })

    it('should have the expected languages for the country', () => {
        expect(1).to.eq(1)
    })
})
```

Logs:

```none
  Running:  Example.test.ts                                                                    (1 of 6)

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     14 seconds                                                                       │
  │ Spec Ran:     Example.test.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
````

In my `support.index.ts`, I have:

```typescript
import installLogsCollector from 'cypress-terminal-report/src/installLogsCollector'

installLogsCollector({})
````

And my `plugins/index.js`:

```javascript
require('cypress-terminal-report/src/installLogsPrinter')(on, {
    printLogsToConsole: 'always'
})
```

Is this expected? Logging this kind of things seems important for quick debugging, I can't understand it's not built-in Cypress.

**Comment by archfz** [comment] 2021-02-25 19:29
Duplicate of https://github.com/archfz/cypress-terminal-report/issues/55 . Please read there what's the status.

**Closed by archfz** 2021-02-25 19:29 UTC

**Comment by Dicee** [comment] 2021-02-25 19:31
Oops, thanks, and sorry. Damn you're fast!
