### ISSUE TITLE
Upgrading from Cypress 9.5.4 to cypress 12.16.0 results in plugin crash w/ typerror

### ISSUE THREAD

**Issue by SketchParker** [archfz/cypress-terminal-report#194] opened 2023-06-29 15:48 UTC
We've been using cypress-terminal-report happily for some time. I've been in the process of migrating from Cypress@9.5.4 to Cypress@12.16.0 

I kick off e2e by using the following command:
`CYPRESS_baseUrl=https://my.url/  yarn cypress open`

and now when running any spec file, we run into a typerror:
`TypeError: Cannot read properties of null (reading 'contentWindow')`

I reinstalled cypress-terminal-report using the following:
`npm i cypress-terminal-report`

Trying to reinstall cypress-terminal-report results in cypress failing to launch, using the same command, with the following error message:
`error Command "cypress" not found.`
Just moments ago, this worked as expected prior to reinstalling the plugin.

_Edit to provide context:_
The error is originating from `node_modules/cypres-terminal-report/src/collector/LogCollectBrowserConsole.js:16:1`
The line that fails is `16 |       const appWindow = docIframe.contentWindow;`

**Comment by SketchParker** [comment] 2023-06-29 19:39
Additional Info:
Downgrading from Cypress@12.16.0 to cypress@9.5.4 results in everything working as expected

**Comment by archfz** [comment] 2023-06-29 19:48
What version of this plugin are you using?

**Comment by SketchParker** [comment] 2023-06-29 20:02
@archfz version 3.5.2

**Comment by archfz** [comment] 2023-06-29 20:27
3.5.2 is not compatible with cypress 10+ see readme please.

You have something more going on. `error Command "cypress" not found.` means that for some reason the command is not found. This plugin doesn't attempt to execute cypress command. So I think the issue is from somewhere else. Maybe try running `CYPRESS_baseUrl=https://my.url/ npx cypress open`

**Comment by SketchParker** [comment] 2023-06-29 20:44
Yup, I'm aware about it being incompatible, however the yarn cypress command only fails when `cypress-terminal-report` version is up-to-date, no other time. I have to downgrade `cypress-terminal-report` in order to make my yarn command work again.

Using `CYPRESS_baseUrl=https://my.url/ npx cypress open` results in a new cypress install with none of my cy.js files being picked up. It does start though, so I'm still trying to track down why it's not working otherwise.

**Comment by archfz** [comment] 2023-06-29 21:06
Remove the plugin and keep the cypress version. See if it still reproduces.

**Comment by SketchParker** [comment] 2023-06-30 19:21
-good-news-everyone.gif-

I uninstalled Cypress, uninstalled the plugin, checked out my repo, reinstalled Cypress, reinstalled the plugin, and everything appears to be working. 

There must have been something wonky in the order in which things happened previously that was causing an issue, as I'm using npm and yarn to manage dependencies, which isn't ideal. I'm going to smoke test everything, but I think I'm in the clear. 

@archfz, we really have appreciated this plugin for some time now, kudos ✅

**Comment by archfz** [comment] 2023-06-30 19:44
Thank you. In that case closing for now.

**Closed by archfz** 2023-06-30 19:44 UTC
