### ISSUE TITLE
ctrLogMessages timing out

### ISSUE THREAD

**Issue by nickpalmer** [archfz/cypress-terminal-report#63] opened 2020-11-24 22:51 UTC
We added a new, fairly long running test to our test suite and we started getting a timeout on that test.

Any suggestions on how to resolve?

```
cy.task('ctrLogMessages') timed out after waiting 60000ms.
```

**Comment by archfz** [comment] 2020-11-25 06:55
What options do you use? Are you logging to files as well? Is the test failing or passing when this timeout occurs while it tries to log? Maybe try enabling the log compacting.

**Comment by archfz** [comment] 2020-11-26 10:00
@nickpalmer Have you found any solutions? Or do you have more info on how to reproduce?

**Comment by archfz** [comment] 2021-02-27 09:03
I will close this for now. Feel free to open another issue with more details as we cannot reproduce this.

**Comment by acornellier** [comment] 2021-04-30 05:20
I also experienced this, with default settings, after updating from 2.0.0 to 2.4.0.

**Comment by archfz** [comment] 2021-05-03 16:27
Really need a way to reproduce this. Any kind of information on what is tested, how many commands there are, how long does the test take without the plugin?

**Comment by archfz** [comment] 2021-05-17 13:58
@acornellier Any additional stuff you could provide for this? Or this still an issue?

**Comment by lopezc184** [comment] 2021-12-24 08:49
I was able to consistently reproduce this error with the code here: https://github.com/cypress-io/cypress/issues/235#issuecomment-1000727681

The test takes 01.65 seconds without the plugin

**Comment by archfz** [comment] 2022-01-06 19:51
I am closing this as per [comment](https://github.com/cypress-io/cypress/issues/235#issuecomment-1006886583) for now. Also we didn't hear back from original author.

If you would like for a workaround using cypress terminal report, we could add a feature to blacklist specs for which to not collect and send logs to terminal. Please open a feature request issue if needed.

**Closed by archfz** 2022-01-06 19:51 UTC
Labels: bug
