### ISSUE TITLE
Crash if error is thrown outside of a test

### ISSUE THREAD

**Issue by villelahdenvuo** [archfz/cypress-terminal-report#152] opened 2022-06-29 15:56 UTC
Here's an error I got (after disabling the terminal report plugin):

<img width="490" alt="image" src="https://user-images.githubusercontent.com/633524/176481037-42f7fa0a-2e67-4353-b68c-1eb79f9f0e83.png">

But when using the terminal report plugin the error is hidden by an error from the terminal report plugin:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/633524/176481298-c2ef3bb9-0bcd-49ee-b7da-0ddd904155a5.png">

Seems like the fileDetails is not available since the error is thrown before the test file is executed correctly. I guess in this case the terminal report should report similarly as Cypress does: 

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/633524/176481590-b98c25ba-54bc-4d36-9cc4-5870020a6fe4.png">

Using Cypress 9.7.0 and cypress-terminal-report 3.5.2

**Comment by archfz** [comment] 2022-07-04 18:14
@kaiyoma isn't ur issue more like https://github.com/archfz/cypress-terminal-report/issues/143 ? Or is it happening in other browsers and non component testing as well?

**Comment by archfz** [comment] 2022-07-04 18:26
@villelahdenvuo I will need you to provide more details, or help me debug this. I don't know how to start reproducing this.

What do you mean by `before the test file is executed correctly`? Where is that `process.env` code? Is it in a spec file, or a dependency to the spec file, or in support.js / command.js?

The thing is that we only send logs on `afterEach` or in case of programmatically skipped tests (for the simple collector). And if your test doesn't actually start because loading the actual spec fails (which defines the test) then neither of the before mentioned steps should be triggered AFAIK. Can you maybe provide a stacktrace for both of the errors in your two screenshots?

**Comment by villelahdenvuo** [comment] 2022-07-04 18:41
@archfz I can reproduce it with a very simple test:
<img width="1023" alt="Screen Shot 2022-07-04 at 20 40 51" src="https://user-images.githubusercontent.com/633524/177205011-de32fa35-ec9a-4a69-9972-9cd5cac627ca.png">

**Comment by villelahdenvuo** [comment] 2022-07-04 18:45
Perhaps this should be reported to Cypress as the original error is being hidden by the error in the after each hook, but regardless the plugin should not crash and should log the error message if possible.

**Comment by kaiyoma** [comment] 2022-07-04 18:54
> @kaiyoma isn't ur issue more like #143 ? Or is it happening in other browsers and non component testing as well?

@archfz I'm not doing component testing. I'm doing normal e2e testing.

**Comment by archfz** [comment] 2022-07-04 22:54
@villelahdenvuo Thanks I will check based on that.

@kaiyoma Do you also have similar issue where an error is overridden by this? You can test by disabling the plugin. If not please open another issue.

**Comment by archfz** [comment] 2022-07-05 21:27
Fix released in 4.0.3

**Closed by archfz** 2022-07-05 21:27 UTC
