### ISSUE TITLE
Component testing file url

### ISSUE THREAD

**Issue by larsk2009** [archfz/cypress-terminal-report#143] opened 2022-05-04 07:31 UTC
Hi,

I am trying to use your library for component testing in Cypress. This sadly gives me an error `invocationDetails.fileUrl is undefined`. The issue only seems to happen in Firefox, which is strange.

I'll add the stack trace below. Any ideas if this is fixable?

```
TypeError: invocationDetails.fileUrl is undefined

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
sendLogsToPrinter@webpack:///./node_modules/cypress-terminal-report/src/collector/LogCollectSimpleControl.js?:40:16
registerTests/<@webpack:///./node_modules/cypress-terminal-report/src/collector/LogCollectSimpleControl.js?:115:12
setRunnable/runnable.fn@http://localhost:61837/__cypress/runner/cypress_runner.js:190621:43
callFn@http://localhost:61837/__cypress/runner/cypress_runner.js:142741:21
../driver/node_modules/mocha/lib/runnable.js/</Runnable.prototype.run@http://localhost:61837/__cypress/runner/cypress_runner.js:142728:13
onRunnableRun/<@http://localhost:61837/__cypress/runner/cypress_runner.js:197531:30
finallyHandler@http://localhost:61837/__cypress/runner/cypress_runner.js:22856:23
tryCatcher@http://localhost:61837/__cypress/runner/cypress_runner.js:26302:23
../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler@http://localhost:61837/__cypress/runner/cypress_runner.js:24237:31
../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise@http://localhost:61837/__cypress/runner/cypress_runner.js:24294:18
../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0@http://localhost:61837/__cypress/runner/cypress_runner.js:24339:10
../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises@http://localhost:61837/__cypress/runner/cypress_runner.js:24419:18
_drainQueueStep@http://localhost:61837/__cypress/runner/cypress_runner.js:21009:12
_drainQueue@http://localhost:61837/__cypress/runner/cypress_runner.js:21002:24
../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues@http://localhost:61837/__cypress/runner/cypress_runner.js:21018:16
Async/this.drainQueues@http://localhost:61837/__cypress/runner/cypress_runner.js:20888:14
```

**Comment by archfz** [comment] 2022-05-04 07:35
Can you please post your cypress, plugin and node version. Plugin options you use. Also a spec example or just how many nested mocha contexts you have in your spec that has this issue. Do all specs fail with this?

**Comment by larsk2009** [comment] 2022-05-04 08:28
Sure:

Cypress: 9.5.2
Your plugin: 3.5.2
Node: v14.19.1

Plugin options: None/default (`require('cypress-terminal-report/src/installLogsPrinter')(on);`, `require("cypress-terminal-report/src/installLogsCollector")();`)

All specs indeed fail, but only on firefox, only 1 of my 2 projects, and only on component testing (so not e2e testing). I have used the file url myself in the past, and the nesting you mention sounds familiar. This is an example spec file nesting:

```ts
describe("gettingStarted", () => {
  beforeEach(() => {
    ....
    mount(<component>, {
      ...
    });
  });

  it("<test case>", () => {
    cy.get("button[data-cy=finished]");
  });
```

There are more test cases, but it already fails on that one. The fail also seems to happen in the `after each` hook so that prevents the other test cases from running.

It seems like a very specific situation, so it might be my setup. I really appreciate your help!

**Comment by archfz** [comment] 2022-05-09 17:32
I have look into the issue and I can confirm as well that `firefox` + `component testing` has no details populated in `invocationDetails`. I have also looked at alternatives and have found none. Even `Cypress.spec.relative` is not properly set, which would be a less reliable alternative otherwise.

This looks like a cypress issue, and I am not sure if any fix can be done on our side. Maybe try to post a bug on cypress side and link here.

**Comment by villelahdenvuo** [comment] 2022-06-29 15:20
<img width="476" alt="image" src="https://user-images.githubusercontent.com/633524/176473834-f9c1b5e3-bfe9-4046-b3e5-1960322f0b52.png">

Also getting this. Normal E2E test with Chrome.

**Comment by archfz** [comment] 2022-06-29 15:23
@villelahdenvuo Please open a new issue, as this is marked for a more specific case with component testing. Also in thay new issue add ample details to be able to reproduce.

**Comment by villelahdenvuo** [comment] 2022-06-29 15:46
Looks like it's a different issue, I'll investigate and open a new issue.

**Comment by larsk2009** [comment] 2022-07-07 07:21
@archfz It seems to work with my preliminary testing, thanks!

**Comment by archfz** [comment] 2022-07-07 07:23
Cool. I will close this for now.

**Closed by archfz** 2022-07-07 07:23 UTC
Labels: bug, requires-cypress-change
